# NumPy · PyTorch · Keras — Practical Guide

A hands-on reference covering the three most important numerical/DL libraries:

| Library | Role |
|---|---|
| **NumPy** | Fast N-dimensional arrays, math, linear algebra |
| **PyTorch** | Tensors + autograd, custom models, research-friendly |
| **Keras (TF2)** | High-level DL API, quick model building, production-ready |

Each section shows the most common patterns with runnable examples.


---
# Part 1 — NumPy

## 1.1 Creating Arrays

The building block of NumPy is `ndarray`. Key creation functions:

| Function | Result |
|---|---|
| `np.array([...])` | from Python list |
| `np.zeros/ones/full` | filled arrays |
| `np.arange` | like `range()` |
| `np.linspace` | evenly spaced floats |
| `np.random.*` | random arrays |


In [6]:
import numpy as np

# From list
a = np.array([1, 2, 3, 4, 5])
print("1-D array:", a)
print("dtype:", a.dtype, "  shape:", a.shape)

# 2-D
m = np.array([[1,2,3],[4,5,6]])
print("\n2-D array:\n", m)
print("shape:", m.shape, "  ndim:", m.ndim)

# Useful constructors
print("\nzeros:", np.zeros((2,3)))
print("ones:",  np.ones((2,3)))
print("identity:\n", np.eye(3))
print("arange:", np.arange(0, 10, 2))
print("linspace:", np.linspace(0, 1, 5))

# Random
rng = np.random.default_rng(42)
print("\nrandom uniform:", rng.random((2,3)).round(3))
print("random normal:", rng.standard_normal((2,3)).round(3))


1-D array: [1 2 3 4 5]
dtype: int64   shape: (5,)

2-D array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)   ndim: 2

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]
identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]

random uniform: [[0.774 0.439 0.859]
 [0.697 0.094 0.976]]
random normal: [[ 0.128 -0.316 -0.017]
 [-0.853  0.879  0.778]]


## 1.2 Indexing, Slicing, Reshaping

```
a[i]          # element
a[i:j]        # slice
a[i, j]       # 2-D element
a[:, j]       # entire column j
a[mask]       # boolean mask
```


In [7]:
import numpy as np

m = np.arange(12).reshape(3, 4)
print("Matrix:\n", m)
print("Row 1:", m[1])
print("Column 2:", m[:, 2])
print("Sub-matrix m[0:2, 1:3]:\n", m[0:2, 1:3])

# Boolean mask
mask = m > 5
print("\nValues > 5:", m[mask])

# Fancy indexing
print("Rows 0 and 2:\n", m[[0,2]])

# Reshape / flatten
flat = m.flatten()
print("\nFlattened:", flat)
print("Reshaped to (2,6):\n", m.reshape(2,6))
print("Transposed:\n", m.T)


Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Row 1: [4 5 6 7]
Column 2: [ 2  6 10]
Sub-matrix m[0:2, 1:3]:
 [[1 2]
 [5 6]]

Values > 5: [ 6  7  8  9 10 11]
Rows 0 and 2:
 [[ 0  1  2  3]
 [ 8  9 10 11]]

Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to (2,6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Transposed:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## 1.3 Vectorised Math & Broadcasting

NumPy applies operations **element-wise** without Python loops.  
**Broadcasting** automatically aligns shapes for arithmetic.

```
(3,4) + (4,)   →  (3,4)   ← row added to each row
(3,1) + (1,4)  →  (3,4)   ← outer-sum
```


In [8]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("a + b  =", a + b)
print("a * b  =", a * b)
print("a ** 2 =", a ** 2)
print("sqrt   =", np.sqrt(a).round(3))
print("exp    =", np.exp(a).round(2))

# Broadcasting
m = np.ones((3, 4))
row = np.array([1, 2, 3, 4])   # shape (4,)
print("\nBroadcast add:\n", m + row)

col = np.array([[10], [20], [30]])  # shape (3,1)
print("\nOuter sum:\n", (row + col))


a + b  = [11 22 33 44]
a * b  = [ 10  40  90 160]
a ** 2 = [ 1  4  9 16]
sqrt   = [1.    1.414 1.732 2.   ]
exp    = [ 2.72  7.39 20.09 54.6 ]

Broadcast add:
 [[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]

Outer sum:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


## 1.4 Aggregations & Linear Algebra

| Operation | Code |
|---|---|
| Sum along axis | `a.sum(axis=0)` |
| Mean / Std | `a.mean()`, `a.std()` |
| Dot product | `a @ b` or `np.dot(a,b)` |
| Matrix inverse | `np.linalg.inv(A)` |
| Eigenvalues | `np.linalg.eig(A)` |
| SVD | `np.linalg.svd(A)` |


In [9]:
import numpy as np

m = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)

print("Sum by row (axis=1):", m.sum(axis=1))
print("Sum by col (axis=0):", m.sum(axis=0))
print("Global mean:", m.mean())
print("Row-wise std:", m.std(axis=1).round(3))
print("Argmax global:", np.argmax(m))

# Linear algebra
A = np.array([[2., 1.], [1., 3.]])
b = np.array([5., 10.])
x = np.linalg.solve(A, b)
print("\nSolve Ax=b:", x)

eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues:", eigvals.round(3))
print("Eigenvectors:\n", eigvecs.round(3))

U, s, Vt = np.linalg.svd(A)
print("\nSVD singular values:", s.round(3))


Sum by row (axis=1): [ 6. 15. 24.]
Sum by col (axis=0): [12. 15. 18.]
Global mean: 5.0
Row-wise std: [0.816 0.816 0.816]
Argmax global: 8

Solve Ax=b: [1. 3.]
Eigenvalues: [1.382 3.618]
Eigenvectors:
 [[-0.851 -0.526]
 [ 0.526 -0.851]]

SVD singular values: [3.618 1.382]


---
# Part 2 — PyTorch

## 2.1 Tensors — the PyTorch ndarray

PyTorch tensors are like NumPy arrays but can live on GPU and support **autograd**.

| NumPy | PyTorch |
|---|---|
| `np.array` | `torch.tensor` |
| `arr.dtype` | `t.dtype` |
| `arr.shape` | `t.shape` |
| `arr.T` | `t.T` or `t.transpose()` |
| `@` | `torch.matmul` or `@` |


In [ ]:
!pip install torch
import torch
import numpy as np

# Create tensors
t = torch.tensor([1.0, 2.0, 3.0])
print("Tensor:", t)
print("dtype:", t.dtype, "  shape:", t.shape)

# Like NumPy constructors
print("zeros:", torch.zeros(2, 3))
print("rand: ", torch.rand(2, 3).round(decimals=3))
print("randn:", torch.randn(2, 3).round(decimals=3))
print("arange:", torch.arange(0, 10, 2))

# From / to NumPy
arr = np.array([4.0, 5.0, 6.0])
t2 = torch.from_numpy(arr)
print("\nFrom numpy:", t2)
print("Back to numpy:", t2.numpy())

# Operations — same as numpy
a = torch.tensor([[1.,2.],[3.,4.]])
b = torch.tensor([[5.,6.],[7.,8.]])
print("\na @ b:\n", a @ b)
print("element-wise *:\n", a * b)


  Using cached torch-2.11.0-cp313-cp313-manylinux_2_28_x86_64.whl.metadata (29 kB)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
  Using cached fsspec-2026.3.0-py3-none-any.whl.metadata (10 kB)
  Using cached cuda_bindings-13.2.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (2.3 kB)
  Using cached nvidia_cudnn_cu13-9.19.0.56-py3-none-manylinux_2_27_x86_64.whl.metadata (1.9 kB)
  Using cached nvidia_cublas-13.1.0.3-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
  Using cached nvidia_cuda_runtime-13.0.96-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
  Using cached nvidia_cufft-12.0.0.61-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
  Using cached nvidia_cuda_cupti-13.0.85-py3-none-manylinux_2_25_x86_64.whl.metadata (1.7 kB)
  Using cached nvidia_cusolver-12.0.4.66-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
  Using cached nvidia_cuda_nvrtc-13.0.88-py3-none-manylinux2010_x86_6

## 2.2 Autograd — Automatic Differentiation

PyTorch tracks operations on tensors with `requires_grad=True` and computes gradients via `.backward()`.

```python
loss.backward()   # fills .grad for all leaf tensors
optimizer.step()  # updates weights
optimizer.zero_grad()  # clear grads before next batch
```


In [6]:
import torch

# Simple scalar gradient
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2 + 2 * x + 1   # y = (x+1)^2
y.backward()
print(f"x={x.item()},  y={y.item()},  dy/dx={x.grad.item()}")
# dy/dx = 2x + 2 = 8

# Vector gradient
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
loss = (x ** 2).sum()   # loss = x0^2 + x1^2 + x2^2
loss.backward()
print("Gradient of sum(x^2):", x.grad)   # should be 2*x

# --- Mini gradient descent example ---
w = torch.tensor(0.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

X = torch.linspace(0, 1, 20)
y_true = 2 * X + 1   # target: w=2, b=1

lr = 0.5
for step in range(100):
    y_pred = w * X + b
    loss = ((y_pred - y_true) ** 2).mean()
    loss.backward()
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad
    w.grad.zero_()
    b.grad.zero_()

print(f"\nLearned w={w.item():.4f}, b={b.item():.4f}  (true: w=2, b=1)")


ModuleNotFoundError: No module named 'torch'

## 2.3 nn.Module — Building Models

All PyTorch models subclass `nn.Module`:

```python
class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc = nn.Linear(in, out)

    def forward(self, x):
        return self.fc(x)
```

| Layer | Description |
|---|---|
| `nn.Linear(in, out)` | Fully connected |
| `nn.ReLU()` | Activation |
| `nn.Sigmoid()` | Activation |
| `nn.Dropout(p)` | Regularization |
| `nn.BatchNorm1d(n)` | Batch normalization |
| `nn.Sequential(...)` | Stack layers inline |


In [7]:
import torch
import torch.nn as nn

# --- Sequential (quick) ---
model = nn.Sequential(
    nn.Linear(10, 64),
    nn.ReLU(),
    nn.Dropout(0.3),
    nn.Linear(64, 32),
    nn.ReLU(),
    nn.Linear(32, 1),
    nn.Sigmoid()
)
x = torch.randn(8, 10)   # batch of 8, 10 features
out = model(x)
print("Output shape:", out.shape)   # (8, 1)

# --- Custom module ---
class TwoLayerNet(nn.Module):
    def __init__(self, in_dim, hidden, out_dim):
        super().__init__()
        self.fc1 = nn.Linear(in_dim, hidden)
        self.fc2 = nn.Linear(hidden, out_dim)
        self.relu = nn.ReLU()

    def forward(self, x):
        return self.fc2(self.relu(self.fc1(x)))

net = TwoLayerNet(10, 32, 3)
out = net(torch.randn(5, 10))
print("Custom net output shape:", out.shape)   # (5, 3)

# Parameter count
total = sum(p.numel() for p in net.parameters())
print("Total params:", total)


ModuleNotFoundError: No module named 'torch'

## 2.4 Full Training Loop

```
for epoch in range(epochs):
    model.train()
    for X_batch, y_batch in loader:
        optimizer.zero_grad()
        loss = criterion(model(X_batch), y_batch)
        loss.backward()
        optimizer.step()
    model.eval()
    # validation ...
```

Common loss functions:

| Task | Loss |
|---|---|
| Binary classification | `nn.BCEWithLogitsLoss()` |
| Multi-class | `nn.CrossEntropyLoss()` |
| Regression | `nn.MSELoss()`, `nn.L1Loss()` |


In [8]:
import torch, torch.nn as nn
from torch.utils.data import TensorDataset, DataLoader
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

# Data
X, y = make_classification(n_samples=600, n_features=10, random_state=42)
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=42)
sc = StandardScaler(); X_tr = sc.fit_transform(X_tr); X_te = sc.transform(X_te)

X_tr_t = torch.tensor(X_tr, dtype=torch.float32)
y_tr_t = torch.tensor(y_tr, dtype=torch.float32).unsqueeze(1)
X_te_t = torch.tensor(X_te, dtype=torch.float32)
y_te_t = torch.tensor(y_te, dtype=torch.float32).unsqueeze(1)

loader = DataLoader(TensorDataset(X_tr_t, y_tr_t), batch_size=32, shuffle=True)

# Model
model = nn.Sequential(nn.Linear(10,32), nn.ReLU(), nn.Linear(32,1))
criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

# Train
for epoch in range(30):
    model.train()
    for Xb, yb in loader:
        optimizer.zero_grad()
        loss = criterion(model(Xb), yb)
        loss.backward()
        optimizer.step()

# Evaluate
model.eval()
with torch.no_grad():
    preds = (torch.sigmoid(model(X_te_t)) > 0.5).float()
    acc = (preds == y_te_t).float().mean()
print(f"Test accuracy: {acc.item():.3f}")


ModuleNotFoundError: No module named 'torch'

## 2.5 Saving & Loading Models

```python
# Save
torch.save(model.state_dict(), 'model.pt')

# Load
model.load_state_dict(torch.load('model.pt'))
model.eval()
```

> Save `state_dict`, not the full model — it's more portable.


In [9]:
import torch, torch.nn as nn, os

model = nn.Sequential(nn.Linear(5, 10), nn.ReLU(), nn.Linear(10, 1))

# Save
torch.save(model.state_dict(), '/tmp/demo_model.pt')
print("Saved. Keys:", list(torch.load('/tmp/demo_model.pt').keys()))

# Load into a new model instance
model2 = nn.Sequential(nn.Linear(5, 10), nn.ReLU(), nn.Linear(10, 1))
model2.load_state_dict(torch.load('/tmp/demo_model.pt'))
model2.eval()

# Verify same output
x = torch.randn(1, 5)
with torch.no_grad():
    match = torch.allclose(model(x), model2(x))
print("Outputs match after load:", match)

os.remove('/tmp/demo_model.pt')


ModuleNotFoundError: No module named 'torch'

---
# Part 3 — Keras (TensorFlow 2)

## 3.1 Sequential API — quickest way to build

```python
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(n,)),
    keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=20, batch_size=32, validation_split=0.2)
```


In [10]:
import numpy as np
# suppress TF info logs
!pip install tensorflow
import os; os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
from tensorflow import keras
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Data
X, y = make_classification(n_samples=800, n_features=10, random_state=42)
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=42)
sc = StandardScaler(); X_tr = sc.fit_transform(X_tr); X_te = sc.transform(X_te)

# Sequential model
model = keras.Sequential([
    keras.layers.Input(shape=(10,)),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

history = model.fit(X_tr, y_tr, epochs=20, batch_size=32,
                    validation_split=0.2, verbose=0)

loss, acc = model.evaluate(X_te, y_te, verbose=0)
print(f"\nTest accuracy: {acc:.3f}")


ModuleNotFoundError: No module named 'tensorflow'

## 3.2 Functional API — multiple inputs/outputs, skip connections

```python
inputs = keras.Input(shape=(n,))
x = keras.layers.Dense(64, activation='relu')(inputs)
outputs = keras.layers.Dense(1)(x)
model = keras.Model(inputs, outputs)
```

Use this when the network is not a simple linear stack.


In [11]:
import os; os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
from tensorflow import keras
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X, y = make_classification(n_samples=800, n_features=10, random_state=0)
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=0)
sc = StandardScaler(); X_tr = sc.fit_transform(X_tr); X_te = sc.transform(X_te)

# Functional API with residual-style skip
inputs = keras.Input(shape=(10,))
x = keras.layers.Dense(64, activation='relu')(inputs)
x = keras.layers.Dropout(0.2)(x)
x = keras.layers.Dense(64, activation='relu')(x)

# Skip connection: project inputs to 64 dims and add
skip = keras.layers.Dense(64)(inputs)
x = keras.layers.Add()([x, skip])
x = keras.layers.Activation('relu')(x)

outputs = keras.layers.Dense(1, activation='sigmoid')(x)

model = keras.Model(inputs, outputs, name='ResidualNet')
model.compile(optimizer=keras.optimizers.Adam(1e-3),
              loss='binary_crossentropy', metrics=['accuracy'])

history = model.fit(X_tr, y_tr, epochs=20, batch_size=32,
                    validation_split=0.2, verbose=0)
_, acc = model.evaluate(X_te, y_te, verbose=0)
print(f"Functional API test accuracy: {acc:.3f}")


ModuleNotFoundError: No module named 'tensorflow'

## 3.3 Common Layers Reference

| Layer | Use case |
|---|---|
| `Dense(n, activation)` | Fully connected |
| `Dropout(rate)` | Regularisation |
| `BatchNormalization()` | Stabilise training |
| `Conv2D(filters, kernel)` | Image feature extraction |
| `MaxPooling2D()` | Spatial downsampling |
| `Flatten()` | 2-D → 1-D |
| `LSTM(units)` | Sequences |
| `Embedding(vocab, dim)` | Word embeddings |

### Activations

| Name | Formula | When |
|---|---|---|
| `relu` | max(0, x) | hidden layers (default choice) |
| `sigmoid` | 1/(1+e⁻ˣ) | binary output |
| `softmax` | eˣᵢ/Σeˣ | multi-class output |
| `tanh` | (eˣ−e⁻ˣ)/(eˣ+e⁻ˣ) | RNNs |
| `linear` | x | regression output |


## 3.4 Callbacks — controlling training

| Callback | Purpose |
|---|---|
| `EarlyStopping(patience=5)` | Stop when val_loss stops improving |
| `ModelCheckpoint('best.keras')` | Save best weights automatically |
| `ReduceLROnPlateau(factor=0.5)` | Halve LR on plateau |
| `TensorBoard(log_dir=...)` | Visualise training in browser |


In [12]:
import os; os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
from tensorflow import keras
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X, y = make_classification(n_samples=1000, n_features=15, random_state=7)
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=7)
sc = StandardScaler(); X_tr = sc.fit_transform(X_tr); X_te = sc.transform(X_te)

model = keras.Sequential([
    keras.layers.Input(shape=(15,)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

callbacks = [
    keras.callbacks.EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True, verbose=1),
    keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, verbose=1),
]

history = model.fit(X_tr, y_tr, epochs=100, batch_size=32,
                    validation_split=0.2, callbacks=callbacks, verbose=0)

_, acc = model.evaluate(X_te, y_te, verbose=0)
epochs_run = len(history.history['loss'])
print(f"Stopped at epoch {epochs_run},  test accuracy: {acc:.3f}")


ModuleNotFoundError: No module named 'tensorflow'

## 3.5 Training Curve Plot

Always visualise loss and accuracy curves to spot overfitting early.


In [13]:
import os; os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X, y = make_classification(n_samples=1000, n_features=15, random_state=7)
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.2, random_state=7)
sc = StandardScaler(); X_tr = sc.fit_transform(X_tr); X_te = sc.transform(X_te)

model = keras.Sequential([
    keras.layers.Input(shape=(15,)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dropout(0.3),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
history = model.fit(X_tr, y_tr, epochs=40, batch_size=32,
                    validation_split=0.2, verbose=0)

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].plot(history.history['loss'],     label='Train loss')
axes[0].plot(history.history['val_loss'], label='Val loss')
axes[0].set_title('Loss curve')
axes[0].set_xlabel('Epoch')
axes[0].legend(); axes[0].grid(True, alpha=0.3)

axes[1].plot(history.history['accuracy'],     label='Train acc')
axes[1].plot(history.history['val_accuracy'], label='Val acc')
axes[1].set_title('Accuracy curve')
axes[1].set_xlabel('Epoch')
axes[1].legend(); axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()
print("Final val accuracy:", round(history.history['val_accuracy'][-1], 3))


ModuleNotFoundError: No module named 'tensorflow'

## 3.6 Saving & Loading (Keras)

```python
# Save entire model (architecture + weights + optimizer)
model.save('model.keras')

# Load
model = keras.models.load_model('model.keras')

# Save/load weights only
model.save_weights('weights.h5')
model.load_weights('weights.h5')
```


In [14]:
import os; os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import numpy as np
import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Input(shape=(5,)),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam', loss='binary_crossentropy')

x_dummy = np.random.randn(4, 5).astype('float32')
before = model.predict(x_dummy, verbose=0)

# Save & reload
model.save('/tmp/demo_keras_model.keras')
loaded = keras.models.load_model('/tmp/demo_keras_model.keras')
after = loaded.predict(x_dummy, verbose=0)

print("Predictions match after load:", np.allclose(before, after))

import shutil; shutil.rmtree('/tmp/demo_keras_model.keras', ignore_errors=True)


ModuleNotFoundError: No module named 'tensorflow'

---
# Quick Comparison Cheatsheet

## When to use what?

| Task | Best choice |
|---|---|
| Array math, data preprocessing | **NumPy** |
| Custom model / research / non-standard architecture | **PyTorch** |
| Quick baseline, standard architectures | **Keras** |
| Production serving (TF SavedModel / TFLite) | **Keras** |
| Fine-tuning HuggingFace models | **PyTorch** |
| Reinforcement learning | **PyTorch** |

## Key concept mapping

| Concept | NumPy | PyTorch | Keras |
|---|---|---|---|
| N-D array | `ndarray` | `Tensor` | `tf.Tensor` |
| Gradient | — | `autograd` | `GradientTape` |
| Layer | — | `nn.Module` | `keras.layers.*` |
| Loss | manual | `nn.MSELoss` etc. | `model.compile(loss=...)` |
| Optimizer | manual | `torch.optim.*` | `model.compile(optimizer=...)` |
| Training loop | manual | manual | `model.fit()` |
| Save model | `np.save` | `torch.save(state_dict)` | `model.save()` |
